import type { NextApiRequest, NextApiResponse } from 'next';
import OpenAI from 'openai';
import {
  type Dictionary,
  getProjectByName,
  type Project,
  type Region,
} from 'src/multimapas/projects';

const client = new OpenAI({});

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type StructuredData = Record<string, Record<string, any>>;

type InsightData = {
  insight: string;
  locationCode: string;
  factCheck: string;
};

const insightJsonSchema = {
  additionalProperties: false,
  required: ['insight', 'locationCode', 'factCheck'],
  type: 'object' as const,
  properties: {
    insight: { type: 'string', description: 'Insight generated by the AI' },
    locationCode: {
      type: 'string',
      description: 'Location code to be highlighted in the map',
    },
    factCheck: {
      type: 'string',
      description: 'Confirmation that all data facts were double-checked',
    },
  },
};

const generalInstructions: string[] = [
  '\n## Instruções gerais para a geração de Insights',
  '1. Analise os padrões nos dados fornecidos com extrema precisão',
  '2. Identifique correlações ou anomalias interessantes',
  '3. Quando mencionar valores específicos como 0 ou 1, VERIFIQUE NOVAMENTE todas as ocorrências desses valores',
  '4. Para valores categóricos ou binários, liste TODAS as localizações que compartilham o mesmo valor',
  '5. Escolha uma localização específica que mereça destaque com base na análise',
  '6. Se afirmar que uma localização é a "única" com certo valor, confirme que isso é verdadeiro',
  '7. Formule um insight claro, conciso e informativo',
  '8. O insight deve ser baseado nos dados e útil para tomada de decisões',
  '9. Use linguagem acessível e direta',
  '10. NÃO cometa erros factuais sobre a distribuição dos dados',
  '11. SEMPRE use o nome da localização em vez do código quando mencionar uma localização',
  '\n## Formato de Resposta\nA resposta deve ser um JSON com as seguintes chaves:\n- insight: O insight gerado pela IA\n- locationCode: O código da localização que foi destacada no insight\n- factCheck: Uma verificação adicional afirmando que você verificou todos os dados mencionados no insight',
];

const buildDictionaryLines = (
  region: Region,
  dictionary: Dictionary
): string[] => {
  const lines: string[] = [
    '\n## Dicionário de Variáveis',
    'Segue a lista das variáveis com suas respectivas descrições e categorias:',
  ];

  for (const variable of region.variables) {
    const info = dictionary[variable.name];
    const varName = info?.variable || variable.name;

    lines.push(`\n### ${varName}`, '\n#### Descrição:');

    if (!info) {
      lines.push('É uma variável numérica e não categórica');
      continue;
    }

    lines.push(info.description || 'Não disponível');

    if (!info.captions || Object.keys(info.captions).length === 0) {
      continue;
    }

    lines.push('\n#### Categorias:');
    for (const [key, val] of Object.entries(info.captions)) {
      lines.push(`  - ${key}: ${val}`);
    }
  }

  return lines;
};

const buildVariableDataLines = (
  region: Region
): { lines: string[]; structuredData: StructuredData } => {
  const lines: string[] = [
    '\n## Dados das Variáveis por Localização\nSegue os valores associados a cada localização:',
  ];
  const structuredData: StructuredData = {};

  for (const variable of region.variables) {
    lines.push(`\n### Variável: ${variable.name}`);
    structuredData[variable.name] = {};

    const entries = Object.entries(variable.data).map(([key, value]) => {
      structuredData[variable.name][key] = value;
      return `- ${key}: ${value}`;
    });

    lines.push(entries.join('\n'));
  }

  return { lines, structuredData };
};

const buildInstructions = (
  project: Project,
  region: Region
): { instructionsArr: string[]; structuredData: StructuredData } => {
  const locationsList = region.locations
    .map((loc) => {
      return `- ${loc.code}: ${loc.name}`;
    })
    .join('\n');

  const instructionsArr: string[] = [
    `# Instruções\n${project.ai!.instructions}`,
    `\n## Contexto da Regionalização\nTipo de regionalização: ${region.name}`,
    '\n## Localizações no Projeto\nSegue a lista das localizações com seus respectivos códigos:',
    locationsList,
  ];

  if (project.dictionary) {
    instructionsArr.push(...buildDictionaryLines(region, project.dictionary));
  }

  const { lines, structuredData } = buildVariableDataLines(region);

  instructionsArr.push(...lines, ...generalInstructions);

  return { instructionsArr, structuredData };
};

const callAI = (
  instructions: string,
  input: string,
  model: string,
  temperature: number
) => {
  return client.responses.create({
    model,
    temperature,
    instructions,
    input,
    text: {
      format: {
        type: 'json_schema',
        name: 'insight_schema',
        schema: insightJsonSchema,
      },
    },
  });
};

const hasUniquenessClaim = (insight: string): boolean => {
  const lower = insight.toLowerCase();
  return (
    lower.includes('única') ||
    lower.includes('unico') ||
    lower.includes('apenas')
  );
};

const tryCorrectInsight = async (
  responseData: InsightData,
  instructionsArr: string[],
  structuredData: StructuredData,
  input: string
): Promise<InsightData | null> => {
  if (!hasUniquenessClaim(responseData.insight)) {
    return null;
  }

  const varMatch = responseData.insight.match(
    /variável\s+[\u2018\u2019'"\u201C\u201D]([^\u2018\u2019'"\u201C\u201D\n]+)[\u2018\u2019'"\u201C\u201D]/i
  );
  const varName = varMatch?.[1];
  const valMatch = responseData.insight.match(/valor (?:de )?(\d+)/i);
  const claimedValue = valMatch?.[1];

  if (!varName || !claimedValue || !structuredData[varName]) {
    return null;
  }

  const locsWithValue = Object.entries(structuredData[varName])
    .filter(([, v]) => {
      return String(v) === claimedValue;
    })
    .map(([code]) => {
      return code;
    });

  if (locsWithValue.length <= 1) {
    return null;
  }

  const correctionLines = [
    '\n## CORREÇÃO DE ERRO FACTUAL IMPORTANTE',
    `Você indicou que a localização ${responseData.locationCode} é a única com valor ${claimedValue} para a variável "${varName}", mas isso é INCORRETO.`,
    `As seguintes localizações têm o valor ${claimedValue} para esta variável: ${locsWithValue.join(', ')}`,
    'Por favor, reformule seu insight considerando TODAS estas localizações e selecione uma delas com base em outros critérios relevantes.',
  ];

  const correctedInstructions = [...instructionsArr, ...correctionLines].join(
    '\n'
  );
  const correctedResponse = await callAI(
    correctedInstructions,
    input,
    'gpt-4o-mini',
    0.5
  );

  return JSON.parse(correctedResponse.output_text) as InsightData;
};

const resolveProjectAndRegion = async (
  projectName: string,
  regionName: string
): Promise<{ project: Project; region: Region } | null> => {
  const project = await getProjectByName(projectName);
  const ai = project?.ai;

  if (!ai) {
    return null;
  }

  if (!ai.instructions || !ai.input) {
    return null;
  }

  const region = project.regions.find((r) => {
    return r.name === regionName;
  });

  return region ? { project, region } : null;
};

export default async (req: NextApiRequest, res: NextApiResponse) => {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed. Use POST.' });
  }

  const resolved = await resolveProjectAndRegion(
    req.query.project as string,
    req.query.region as string
  );

  if (!resolved) {
    return res
      .status(400)
      .json({ error: 'Project or region not found, or missing AI config.' });
  }

  const { project, region } = resolved;
  const { instructionsArr, structuredData } = buildInstructions(
    project,
    region
  );
  const instructions = instructionsArr.join('\n');
  const { ai } = project;

  const aiResponse = await callAI(
    instructions,
    ai!.input,
    ai!.model || 'gpt-4o-mini',
    ai!.temperature || 0.7
  );

  try {
    const responseData = JSON.parse(aiResponse.output_text) as InsightData;
    const corrected = await tryCorrectInsight(
      responseData,
      instructionsArr,
      structuredData,
      ai!.input
    );

    return res
      .status(200)
      .json({ ...(corrected ?? responseData), instructions, input: ai!.input });
  } catch {
    return res.status(500).json({
      error: 'Failed to process AI response',
      aiResponse: aiResponse.output_text,
    });
  }
};
