import { NextApiRequest, NextApiResponse } from 'next';
import OpenAI from 'openai';
import { getProjectByName } from 'src/multimapas/projects';

const client = new OpenAI({});

export default async (req: NextApiRequest, res: NextApiResponse) => {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed. Use POST.' });
  }

  const project = await getProjectByName(req.query.project as string);

  if (!project?.ai?.instructions || !project?.ai?.input) {
    return res
      .status(400)
      .json({ error: 'Project does not have AI instructions or input.' });
  }

  const region = project.regions.find((region) => {
    return region.name === req.query.region;
  });

  if (!region) {
    return res.status(400).json({ error: 'Region not found.' });
  }

  const instructionsArr = [project.ai.instructions];

  instructionsArr.push(
    '\nSegue a lista das localizações que estão no projeto e os seus respectivos códigos:'
  );
  for (const locations of region.locations) {
    instructionsArr.push(`- ${locations.code}: ${locations.name}`);
  }

  instructionsArr.push(
    '\nSegue a lista das variáveis que estão no projeto e os valores que estão associados a cada uma das localizações:'
  );
  for (const variable of region.variables) {
    instructionsArr.push(`\nVariável: ${variable.name}`);
    for (const [key, value] of Object.entries(variable.data)) {
      instructionsArr.push(`- ${key}: ${value}`);
    }
  }

  const instructions = instructionsArr.join('\n');

  const input = project.ai.input;

  const aiResponse = await client.responses.create({
    model: 'gpt-4o-mini',
    temperature: project?.ai?.temperature || 0.7,
    instructions,
    input,
    text: {
      format: {
        type: 'json_schema',
        name: 'insight_schema',
        schema: {
          additionalProperties: false,
          required: ['insight', 'locationCode'],
          type: 'object',
          properties: {
            insight: {
              type: 'string',
              description: 'Insight generated by the AI',
            },
            locationCode: {
              type: 'string',
              description: 'Location code to be highlighted in the map',
            },
          },
        },
      },
    },
  });

  const response = {
    ...JSON.parse(aiResponse.output_text),
    instructions,
    input,
  };

  return res.status(200).json(response);
};
