# -*- coding: utf-8 -*-
"""NC_to_GJ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OYRdW-mMlXe4_HvhrCj8GhSuCLW5Ygfk
"""

import xarray as xr
import numpy as np
import json
import geopandas as gpd
import matplotlib.pyplot as plt
import xarray as xr
import numpy as np
import os

# Coloque o caminho correto para a pasta onde esta o arquivo nc de T2
ds = xr.open_dataset("./t2_global.nc")
data = ds["d2m"].values
lat = ds["latitude"].values
lon = ds["longitude"].values

data2d = data[0]
features = []
for i in range(len(lat)):
    for j in range(len(lon)):
        v = float(data2d[i, j])
        if np.isnan(v):
            continue
        features.append({
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [float(lon[j]), float(lat[i])]
            },
            "properties": {"tp": v}
        })

geojson = {"type": "FeatureCollection", "features": features}

with open("d2m.geojson", "w") as f:
    json.dump(geojson, f, indent=2)

print("pontos gerados:", len(features))

gdf = gpd.read_file("d2m.geojson")
tp = gdf["tp"].fillna(0)
tp = np.where(tp < 0, 0, tp)

plt.scatter(gdf.geometry.x, gdf.geometry.y, c=tp)
plt.title("GeoJSON - T2")
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.show()
