# Only add packages that are Node.js projects
packages:
  - subsystem/aggrada-core
  - subsystem/aggrada-outsource
  - subsystem/aggrada-ingestor
  - subsystem/aggrada-aggregator
  - subsystem/api
  - subsystem/app
  - subsystem/postgresdb
  - subsystem/website
  - subsystem/website-polygons
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
